exports.run = (client, message, args) => {
  if (args[0] == null) {
    return message.channel.send('```Markdown\n#Welcome to the AllStar bot help guide\n\nTo enable us to properly help you please select frome one of the following options.\n\n1. For help with "Moderation" commands please use: !!help mod\n2. For help with "Fun" commands please use: !!help fun\n3. For help with "Community" commands please use: !!help community or !!help community2 for page 2```');
  } else if (args[0] == 'mod') {
    return message.channel.send('```Markdown\n#Moderation Commands\n\nThese commands are limited to members of the staff team only.\n\n[1]Kick - This command enables you to kick a mentioned member. \nUsage: !!kick @skenk\n\n[2]Purge - Removes a specified number of messages from the text chat. \nUsage: !!purge 100\n\n[3]Reload - Reloads a specfied command after changes have been applied.\nUsage: !!reload help```');
  } else if (args[0] == 'fun') {
    return message.channel.send('```Markdown\n#Fun Commands (Page 1 of 2)\n\nThese commands can be used by all members of the server\n\n[1]Slap - This command slaps another user (Slaps are not tracked in this version of the bot).\nUsage: !!slap @skenk\n\n[2]Rate - Rates whatever you say on a scale of 0 - 10.\nUsage: !!rate input\n\n[3]Date - Gives you the number of months untill next year.\nUsage: !!date\n\n[4]Roulette - Play Russain roulette with the chance to increase your wallet.\nUsage: !!roulette 50\n\n[5]Pickpocket - Have a chance at picking the pocket of another member\nUsage: !!pickpocket @cobra```');
  } else if (args[0] == 'fun2'){
    return message.channel.send('```Markdown\n#Fun Commands (Page 2 of 2)\n\nThese commands can be used by all members of the server\n\n[7]Random Trump Quoute - Sends you a random Donald Trump quote.\nUsage: !!randomtrump\n\n[8]Random Cat Fact - Get a random cat fact\nUsage: !!catfact\n\n[9]Minecraft Skin - Give the command a minecraft user and get their skin\nUsage: !!mcskin skenk```');
  } else if (args[0] == 'community') {
    return message.channel.send('```Markdown\n#Community Commands(Page 1 of 2)\n\nMost of these commands can be used by all members of the server. If a command requires a role it will be denoted with an asterix(*).\n\n[1]Contact - This command allows you to contact the developer of the bot, This can be used to report bugs or make suggestions.\nUsage: !!contact whatever you want to say here\n\n[2]Play - Adds music to the queue via URL or search term (Valid Services include: YouTube, Vimeo, YoKu).\nUsage: !!play <https://youtu.be/FG9M0aEpJGE> OR <Search Term>\n\n[3]Skip - This command will skip a number of songs through the queue.\nUsage: !!skip 1\n\n[4]Queue - Displays the current music Queue.\nUsage: !!queue\n\n[5]Pause - Pauses the current song.\nUsage: !!pause\n\n[6]Resume - Resumes the current song.\nUsage: !!resume```');
  } else if (args[0] == 'community2') {
    return message.channel.send('```Markdown\n#Community Commands(Page 2 of 2)\n\nThese commands can be used by all members of the server\n\n[7]Volume - Changes the volume of the bot.\nUsage: !!volume <Number between 1 and 200>.\n\n[8]Leave - Clears the song queue and leaves the channel.\nUsage: !!leave\n\n[10]Clear Queue - Clears the song queue.\nUsage: !!clearqueue\n\n[11]About - Displays some information about the bot.\nUsage: !!about\n\n[12]Stats - Displays user stats.\nUsage: !!stats OR !!stats @skenk```')
  } else if (args[0] == 'weed') {
    return message.channel.send('```Markdown\n#Weed Commands(Page 1 of 2)\n\nThese commands can be used by all members of the server\n\n[1]420 Code - Provides a link to the 420 Code guide\nUsage: !!420code\n\n[2]Chill n Toke - Sends you a link to Trees Radio\nUsage: !!chillntoke\n\n[3]How 2 Roll - Links a pretty decent guide on rolling a joint\nUsage: !!how2roll\n\n[4]Im Baked - Links you to a random website thats pretty entertaining whilst baked.\nUsage: !!imbaked\n\n[5]Strain - Uses the Cannabis Reports API to search your strain.\nUsage: !!strain kush.```')
  } else if (args[0] == 'weed2') {
    return message.channel.send('```Markdown\n#Weed Commands(Page 2 of 2)\n\nThese commands can be used by all members of the server\n\n[6]Trees - This commands links the top five posts from the r/trees hot page\nUsage: !!trees```')
  }
}
